[language-server.lua-language-server.config]
Lua = { telemetry = { enable = true } }

[language-server.yaml-language-server.config]
redhat = { telemetry = { enabled = false } }
yaml = { keyOrdering = false, format = { enable = true } }

[language-server.nixd]
command = "nixd"

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[[language]]
name = "nix"
indent = { tab-width = 2, unit = " " }
auto-format = true
formatter = { command = "nixfmt", args = ["--quiet"] }
language-servers = ["nixd"]

[language-server.rust-analyzer.config]
imports = { granularity = { group = "module" }, prefix = "self" }
cargo = { allFeatures = true, targetDir = true, buildScripts = { enable = true }, loadOutDirsFromCheck = true, runBuildScripts = true }
check = { command = "clippy", allTargets = false }
procMacro = { enable = true, ignored = { leptos_macro = ["server"] } }



[[language]]
name = "javascript"
auto-format = true
language-servers = ["biome"]

[[language]]
name = "typescript"
auto-format = true
language-servers = ["biome"]

[[language]]
name = "jsx"
auto-format = true
language-servers = ["biome"]

[[language]]
name = "json"
file-types = ["json"]
scope = "source.json"
auto-format = true
language-servers = ["biome"]

[[language]]
name = "rust"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'


[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"] }

[[language]]
name = "javascript"
formatter = { command = "biome", args = ["format", "--stdin-file-path=x.js"] }

[[language]]
name = "typescript"
formatter = { command = "biome", args = ["format", "--stdin-file-path=x.ts"] }

[[language]]
name = "jsx"
formatter = { command = "biome", args = ["format", "--stdin-file-path=x.jsx"] }

[[language]]
name = "json"
formatter = { command = "biome", args = ["format", "--stdin-file-path=x.json"] }