anchor_to_edges = true
position = "top"
height = 8

[[start]]
type = "workspaces"
all_monitors = false
hidden = [
  "special:scratch_term",
  "special:scratch_volume",
]

# [[start]]
# type = "launcher"
# favorites = [
#   "brave",
#   "warp",
#   "telegram-desktop",
# ]
# show_names = false
# show_icons = true

[[end]]
type = "volume"
format = "{icon} {percentage}%"
max_volume = 150

[end.icons]
volume_high = "󰕾"
volume_medium = "󰖀"
volume_low = "󰕿"
muted = "󰝟"

# [[end]]
# type = "clipboard"
# max_items = 3

[[end]]
class = 'power-menu'
# tooltip = '''Up: {{30000:uptime -p | cut -d ' ' -f2-}}'''
type = 'custom'

[[end.bar]]
label = ''
name = 'power-btn'
on_click = 'popup:toggle'
type = 'button'

[[end.popup]]
orientation = 'vertical'
type = 'box'

# [[end.popup.widgets]]
# label = 'Power menu'
# name = 'header'
# type = 'label'

[[end.popup.widgets]]
type = 'box'

[[end.popup.widgets.widgets]]
class = 'power-btn'
label = ''''''
on_click = '!shutdown now'
type = 'button'

[[end.popup.widgets.widgets]]
class = 'power-btn'
label = ''''''
on_click = '!reboot'
type = 'button'

[[end]]
type = "clock"

# [[end]]
# type = "upower"
# format = "{percentage}%"
