# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  zellij-room = {
    pname = "zellij-room";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "rvcas";
      repo = "room";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-LWmtaFuxbFyHWa7BMEVvp7rHmm1JLg0SjJFi/V98VKY=";
    };
  };
  zjstatus = {
    pname = "zjstatus";
    version = "v0.16.0";
    src = fetchFromGitHub {
      owner = "dj95";
      repo = "zjstatus";
      rev = "v0.16.0";
      fetchSubmodules = false;
      sha256 = "sha256-3Zo8kD/NQhHTkeVSRCSXYX86fnZyk/EJ15pH365tZY0=";
    };
  };
}
