return {
  {
    "windwp/nvim-ts-autotag",
    dependencies = "nvim-treesitter/nvim-treesitter",
    event = "VeryLazy",
    opts = {},
  },
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
      "nvim-treesitter/nvim-treesitter-textobjects",
      "nvim-treesitter/nvim-treesitter-context",
      "RRethy/nvim-treesitter-textsubjects",
      "hiphish/rainbow-delimiters.nvim",
      "Wansmer/sibling-swap.nvim",
      "JoosepAlviste/nvim-ts-context-commentstring",
      "IndianBoy42/tree-sitter-just",
    },
    lazy = false,
    config = function()
      require("nvim-treesitter.install").compilers = { "gcc" }

      local configs = require("nvim-treesitter.configs")
      configs.setup({
        indent = { enable = true },
        highlight = { enable = true },
        autopairs = { enable = true },

        ensure_installed = {
          "c",
          "lua",
          "vim",
          "vimdoc",
          "query",
          "bash",
          "cmake",
          "commonlisp",
          "cpp",
          "css",
          "csv",
          "diff",
          "dockerfile",
          "fish",
          "git_config",
          "git_rebase",
          "gitattributes",
          "gitcommit",
          "gitignore",
          "glsl",
          "graphql",
          "groovy",
          "hocon",
          "hlsl",
          "hocon",
          "html",
          "http",
          "hyprlang",
          "ini",
          "java",
          "javascript",
          "jq",
          "jsdoc",
          "json5",
          "jsonc",
          "kdl",
          "kotlin",
          "lua",
          "luadoc",
          "luap",
          "make",
          "markdown",
          "markdown_inline",
          "meson",
          "nix",
          "odin",
          "properties",
          "proto",
          "printf",
          "python",
          "ron",
          "rust",
          "scss",
          "slint",
          "smithy",
          "sql",
          "ssh_config",
          "strace",
          "textproto",
          "toml",
          "tsx",
          "typescript",
          "typst",
          "udev",
          "wgsl",
          "wgsl_bevy",
          "xml",
          "yaml",
          "zig",
        },
      })

      require("tree-sitter-just").setup({})

      require("treesitter-context").setup({})

      require("sibling-swap").setup({})
    end,
  },
}