# theme = "kanagawa_dragon" # inlay hints are broken
theme = "autumn_night_variant"

[editor]
line-number = "relative"
auto-format = false
# mouse = false
shell = ["dash", "-c"]
default-line-ending = "lf"
# color-modes = true
# auto-save = true
completion-replace = true
bufferline = "multiple"
completion-timeout = 50
idle-timeout = 200

[editor.auto-save]
focus-lost = true
after-delay = { enable = true, timeout = 1500 }

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "spinner", "version-control"]
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"
separator = "│"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"
nnbsp = "␣"
tab = " "
newline = " "
tabpad = " "

[editor.indent-guides]
render = true
# character = "⸽"
character = "▏"
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.normal]
o = [":o", "insert_register"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"
